// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*agentCredentialResource)(nil)
	_ resource.ResourceWithConfigure   = (*agentCredentialResource)(nil)
	_ resource.ResourceWithImportState = (*agentCredentialResource)(nil)
)

type agentCredentialResource struct {
	client *pgbeam.Client
}

type agentCredentialResourceModel struct {
	ID               types.String `tfsdk:"id"`
	ProjectID        types.String `tfsdk:"project_id"`
	PolicyProfileID  types.String `tfsdk:"policy_profile_id"`
	Name             types.String `tfsdk:"name"`
	PgUsername       types.String `tfsdk:"pg_username"`
	Status           types.String `tfsdk:"status"`
	PrincipalType    types.String `tfsdk:"principal_type"`
	AuthMethod       types.String `tfsdk:"auth_method"`
	LastUsedAt       types.String `tfsdk:"last_used_at"`
	ExpiresAt        types.String `tfsdk:"expires_at"`
	CreatedAt        types.String `tfsdk:"created_at"`
	UpdatedAt        types.String `tfsdk:"updated_at"`
	ConnectionString types.String `tfsdk:"connection_string"`
	McpURL           types.String `tfsdk:"mcp_url"`
	McpToken         types.String `tfsdk:"mcp_token"`
}

func NewAgentCredentialResource() resource.Resource {
	return &agentCredentialResource{}
}

func (r *agentCredentialResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_agent_credential"
}

func (r *agentCredentialResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a scoped agent credential (a PgBeam-issued Postgres login plus a hosted MCP token) for an AI agent. The connection string and MCP token are one-time secrets returned only at creation and exposed as sensitive computed outputs; they cannot be retrieved again. To rotate the secrets, taint/replace the resource (or use the rotate endpoint out of band).",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique agent credential identifier (prefixed).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Description: "Owning project ID.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"policy_profile_id": schema.StringAttribute{
				Description: "Policy profile enforced for this credential.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Human-readable label for the credential.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"pg_username": schema.StringAttribute{
				Description: "The Postgres username this credential presents to the proxy.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"status": schema.StringAttribute{
				Description: "Lifecycle status of the credential.",
				Optional:    true,
				Computed:    true,
			},
			"principal_type": schema.StringAttribute{
				Description: "Whether this credential represents an autonomous agent or a human operator.",
				Optional:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"auth_method": schema.StringAttribute{
				Description: "Postgres auth method the proxy presents for this credential.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_used_at": schema.StringAttribute{
				Description: "When the credential was last used to connect, if ever.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"expires_at": schema.StringAttribute{
				Description: "When the credential expires and becomes unusable. Null means it never expires. Enforcement is fail-closed in the proxy the instant this time passes, before any cleanup sweep runs.",
				Optional:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created_at": schema.StringAttribute{
				Description: "When the credential was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the credential was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"connection_string": schema.StringAttribute{
				Description: "One-time guarded Postgres connection string for this agent credential (shown once).",
				Computed:    true,
				Sensitive:   true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"mcp_url": schema.StringAttribute{
				Description: "Hosted agent-database MCP endpoint for this project. Use with the mcp_token as a bearer token.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"mcp_token": schema.StringAttribute{
				Description: "One-time bearer token for the hosted MCP endpoint (shown once).",
				Computed:    true,
				Sensitive:   true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *agentCredentialResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *agentCredentialResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan agentCredentialResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.CreateAgentCredentialRequest{
		PolicyProfileId: plan.PolicyProfileID.ValueString(),
		Name:            plan.Name.ValueString(),
	}

	if !plan.PrincipalType.IsNull() && !plan.PrincipalType.IsUnknown() {
		v := pgbeam.CreateAgentCredentialRequestPrincipalType(plan.PrincipalType.ValueString())
		createReq.PrincipalType = &v
	}

	if !plan.ExpiresAt.IsNull() && !plan.ExpiresAt.IsUnknown() {
		expiresAtTime, err := time.Parse(time.RFC3339, plan.ExpiresAt.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Invalid expires_at", "Expected an RFC3339 timestamp: "+err.Error())
			return
		}
		createReq.ExpiresAt = &expiresAtTime
	}

	result, err := r.client.Agents.CreateAgentCredential(ctx, plan.ProjectID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating agent credential", err.Error())
		return
	}

	updateReq := pgbeam.UpdateAgentCredentialStatusRequest{}
	needsPostCreateUpdate := false
	if !plan.Status.IsNull() && !plan.Status.IsUnknown() {
		v := pgbeam.UpdateAgentCredentialStatusRequestStatus(plan.Status.ValueString())
		updateReq.Status = v
		needsPostCreateUpdate = true
	}
	if needsPostCreateUpdate {
		if _, err := r.client.Agents.UpdateAgentCredentialStatus(ctx, plan.ProjectID.ValueString(), result.Credential.Id, updateReq); err != nil {
			resp.Diagnostics.AddError("Error setting rate limits on newly created agent credential", err.Error())
			return
		}
		updated, err := r.client.Agents.GetAgentCredential(ctx, plan.ProjectID.ValueString(), result.Credential.Id)
		if err != nil {
			resp.Diagnostics.AddError("Error reading agent credential after rate limit update", err.Error())
			return
		}
		result.Credential = *updated
	}

	plan.ID = types.StringValue(result.Credential.Id)
	r.mapAgentCredentialToState(&plan, &result.Credential)

	plan.ConnectionString = types.StringValue(result.ConnectionString)

	plan.McpURL = types.StringValue(result.McpUrl)

	plan.McpToken = types.StringValue(result.McpToken)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *agentCredentialResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state agentCredentialResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	AgentCredential, err := r.client.Agents.GetAgentCredential(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading agent credential", err.Error())
		return
	}

	r.mapAgentCredentialToState(&state, AgentCredential)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *agentCredentialResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan agentCredentialResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state agentCredentialResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateReq := pgbeam.UpdateAgentCredentialStatusRequest{}
	hasChanges := false

	if !plan.Status.Equal(state.Status) {
		v := pgbeam.UpdateAgentCredentialStatusRequestStatus(plan.Status.ValueString())
		updateReq.Status = v
		hasChanges = true
	}

	if hasChanges {
		_, err := r.client.Agents.UpdateAgentCredentialStatus(ctx, state.ProjectID.ValueString(), state.ID.ValueString(), updateReq)
		if err != nil {
			resp.Diagnostics.AddError("Error updating agent credential", err.Error())
			return
		}
	}

	AgentCredential, err := r.client.Agents.GetAgentCredential(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading agent credential after update", err.Error())
		return
	}

	plan.ID = state.ID
	plan.ConnectionString = state.ConnectionString
	plan.McpURL = state.McpURL
	plan.McpToken = state.McpToken
	r.mapAgentCredentialToState(&plan, AgentCredential)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *agentCredentialResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state agentCredentialResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Agents.RevokeAgentCredential(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting agent credential", err.Error())
	}
}

func (r *agentCredentialResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: project_id/agent_id")
		return
	}

	projectID := parts[0]
	agentID := parts[1]

	AgentCredential, err := r.client.Agents.GetAgentCredential(ctx, projectID, agentID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing agent credential", err.Error())
		return
	}

	var state agentCredentialResourceModel
	state.ID = types.StringValue(AgentCredential.Id)
	state.ProjectID = types.StringValue(projectID)
	r.mapAgentCredentialToState(&state, AgentCredential)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *agentCredentialResource) mapAgentCredentialToState(state *agentCredentialResourceModel, resp *pgbeam.AgentCredential) {
	state.ProjectID = types.StringValue(resp.ProjectId)
	state.PolicyProfileID = types.StringValue(resp.PolicyProfileId)
	state.Name = types.StringValue(resp.Name)
	state.PgUsername = types.StringValue(resp.PgUsername)
	if string(resp.Status) != "" {
		state.Status = types.StringValue(string(resp.Status))
	} else {
		state.Status = types.StringNull()
	}
	if resp.PrincipalType != nil && string(*resp.PrincipalType) != "" {
		state.PrincipalType = types.StringValue(string(*resp.PrincipalType))
	} else {
		state.PrincipalType = types.StringNull()
	}
	if resp.AuthMethod != nil && string(*resp.AuthMethod) != "" {
		state.AuthMethod = types.StringValue(string(*resp.AuthMethod))
	} else {
		state.AuthMethod = types.StringNull()
	}
	if resp.LastUsedAt != nil {
		state.LastUsedAt = types.StringValue(resp.LastUsedAt.Format(time.RFC3339))
	} else {
		state.LastUsedAt = types.StringNull()
	}
	if resp.ExpiresAt != nil {
		state.ExpiresAt = types.StringValue(resp.ExpiresAt.Format(time.RFC3339))
	} else {
		state.ExpiresAt = types.StringNull()
	}
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
