// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*anomalyRuleResource)(nil)
	_ resource.ResourceWithConfigure   = (*anomalyRuleResource)(nil)
	_ resource.ResourceWithImportState = (*anomalyRuleResource)(nil)
)

type anomalyRuleResource struct {
	client *pgbeam.Client
}

type anomalyRuleResourceModel struct {
	ID             types.String  `tfsdk:"id"`
	ProjectID      types.String  `tfsdk:"project_id"`
	CredentialID   types.String  `tfsdk:"credential_id"`
	Metric         types.String  `tfsdk:"metric"`
	SigmaThreshold types.Float64 `tfsdk:"sigma_threshold"`
	Floor          types.Float64 `tfsdk:"floor"`
	Enabled        types.Bool    `tfsdk:"enabled"`
	CreatedAt      types.String  `tfsdk:"created_at"`
	UpdatedAt      types.String  `tfsdk:"updated_at"`
}

func NewAnomalyRuleResource() resource.Resource {
	return &anomalyRuleResource{}
}

func (r *anomalyRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_anomaly_rule"
}

func (r *anomalyRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages an anomaly rule: the sensitivity of one detection metric for one project, or for one agent credential in it. Without a rule every metric resolves to the deployment default, so a credential that legitimately runs at 3am cannot be exempted and a noisy one cannot be loosened. Note the polarity of enabled: the rule IS the switch, so enabled=false silences the metric for that scope rather than deactivating the rule. One rule exists per (project, credential, metric); a second one for the same scope is a conflict. Detection runs in the control plane and re-reads the rules on every pass, so a write takes effect at the next detection pass rather than being pushed to the proxy.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique anomaly rule identifier.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Description: "Project the rule belongs to.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"credential_id": schema.StringAttribute{
				Description: "Agent credential the rule applies to. Null applies it to every credential in the project.\n",
				Optional:    true,
			},
			"metric": schema.StringAttribute{
				Description: "One of the five detection metrics. A rule retunes how sensitive one of them is; it adds no detection algorithm and no alert kind.\n",
				Required:    true,
			},
			"sigma_threshold": schema.Float64Attribute{
				Description: "N in the \"mean + N * dispersion\" spike rule. Null leaves the deployment default in place.\n",
				Optional:    true,
			},
			"floor": schema.Float64Attribute{
				Description: "Absolute floor below which the metric never alerts. Null leaves the deployment default in place. Only queries_per_hour, bytes_per_hour and errors_per_hour have a floor.\n",
				Optional:    true,
			},
			"enabled": schema.BoolAttribute{
				Description: "False silences this metric for this scope. Note the polarity is the opposite of honeytokens.enabled: the rule IS the switch, so disabling it disables the metric rather than deactivating the rule.\n",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
			},
			"created_at": schema.StringAttribute{
				Description: "When the rule was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the rule was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *anomalyRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *anomalyRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan anomalyRuleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.AnomalyRuleInput{
		Metric: pgbeam.AnomalyMetric(plan.Metric.ValueString()),
	}

	if !plan.CredentialID.IsNull() && !plan.CredentialID.IsUnknown() {
		v := plan.CredentialID.ValueString()
		createReq.CredentialId = &v
	}

	if !plan.SigmaThreshold.IsNull() && !plan.SigmaThreshold.IsUnknown() {
		v := plan.SigmaThreshold.ValueFloat64()
		createReq.SigmaThreshold = &v
	}

	if !plan.Floor.IsNull() && !plan.Floor.IsUnknown() {
		v := plan.Floor.ValueFloat64()
		createReq.Floor = &v
	}

	if !plan.Enabled.IsNull() && !plan.Enabled.IsUnknown() {
		v := plan.Enabled.ValueBool()
		createReq.Enabled = &v
	}

	result, err := r.client.Anomalies.CreateAnomalyRule(ctx, plan.ProjectID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating anomaly rule", err.Error())
		return
	}

	plan.ID = types.StringValue(result.Id)
	r.mapAnomalyRuleToState(&plan, result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *anomalyRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state anomalyRuleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	AnomalyRule, err := r.client.Anomalies.GetAnomalyRule(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading anomaly rule", err.Error())
		return
	}

	r.mapAnomalyRuleToState(&state, AnomalyRule)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *anomalyRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan anomalyRuleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state anomalyRuleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	hasChanges := !plan.CredentialID.Equal(state.CredentialID) ||
		!plan.Metric.Equal(state.Metric) ||
		!plan.SigmaThreshold.Equal(state.SigmaThreshold) ||
		!plan.Floor.Equal(state.Floor) ||
		!plan.Enabled.Equal(state.Enabled)

	updateReq := pgbeam.AnomalyRuleInput{
		Metric: pgbeam.AnomalyMetric(plan.Metric.ValueString()),
	}

	if !plan.CredentialID.IsNull() && !plan.CredentialID.IsUnknown() {
		v := plan.CredentialID.ValueString()
		updateReq.CredentialId = &v
	}

	if !plan.SigmaThreshold.IsNull() && !plan.SigmaThreshold.IsUnknown() {
		v := plan.SigmaThreshold.ValueFloat64()
		updateReq.SigmaThreshold = &v
	}

	if !plan.Floor.IsNull() && !plan.Floor.IsUnknown() {
		v := plan.Floor.ValueFloat64()
		updateReq.Floor = &v
	}

	if !plan.Enabled.IsNull() && !plan.Enabled.IsUnknown() {
		v := plan.Enabled.ValueBool()
		updateReq.Enabled = &v
	}

	if hasChanges {
		_, err := r.client.Anomalies.UpdateAnomalyRule(ctx, state.ProjectID.ValueString(), state.ID.ValueString(), updateReq)
		if err != nil {
			resp.Diagnostics.AddError("Error updating anomaly rule", err.Error())
			return
		}
	}

	AnomalyRule, err := r.client.Anomalies.GetAnomalyRule(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading anomaly rule after update", err.Error())
		return
	}

	plan.ID = state.ID
	r.mapAnomalyRuleToState(&plan, AnomalyRule)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *anomalyRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state anomalyRuleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Anomalies.DeleteAnomalyRule(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting anomaly rule", err.Error())
	}
}

func (r *anomalyRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: project_id/anomaly_rule_id")
		return
	}

	projectID := parts[0]
	anomalyRuleID := parts[1]

	AnomalyRule, err := r.client.Anomalies.GetAnomalyRule(ctx, projectID, anomalyRuleID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing anomaly rule", err.Error())
		return
	}

	var state anomalyRuleResourceModel
	state.ID = types.StringValue(AnomalyRule.Id)
	state.ProjectID = types.StringValue(projectID)
	r.mapAnomalyRuleToState(&state, AnomalyRule)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *anomalyRuleResource) mapAnomalyRuleToState(state *anomalyRuleResourceModel, resp *pgbeam.AnomalyRule) {
	state.ProjectID = types.StringValue(resp.ProjectId)
	if resp.CredentialId != nil {
		state.CredentialID = types.StringValue(*resp.CredentialId)
	} else {
		state.CredentialID = types.StringNull()
	}
	if string(resp.Metric) != "" {
		state.Metric = types.StringValue(string(resp.Metric))
	} else {
		state.Metric = types.StringNull()
	}
	if resp.SigmaThreshold != nil {
		state.SigmaThreshold = types.Float64Value(*resp.SigmaThreshold)
	} else {
		state.SigmaThreshold = types.Float64Null()
	}
	if resp.Floor != nil {
		state.Floor = types.Float64Value(*resp.Floor)
	} else {
		state.Floor = types.Float64Null()
	}
	state.Enabled = types.BoolValue(resp.Enabled)
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
