// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*databaseResource)(nil)
	_ resource.ResourceWithConfigure   = (*databaseResource)(nil)
	_ resource.ResourceWithImportState = (*databaseResource)(nil)
)

type databaseResource struct {
	client *pgbeam.Client
}

type databaseResourceModel struct {
	ID               types.String `tfsdk:"id"`
	ProjectID        types.String `tfsdk:"project_id"`
	ConnectionString types.String `tfsdk:"connection_string"`
	Host             types.String `tfsdk:"host"`
	Port             types.Int64  `tfsdk:"port"`
	Name             types.String `tfsdk:"name"`
	Username         types.String `tfsdk:"username"`
	SSLMode          types.String `tfsdk:"ssl_mode"`
	Role             types.String `tfsdk:"role"`
	PoolRegion       types.String `tfsdk:"pool_region"`
	QueryTimeoutMs   types.Int64  `tfsdk:"query_timeout_ms"`
	AutoReadRouting  types.Bool   `tfsdk:"auto_read_routing"`
	CacheConfig      types.Object `tfsdk:"cache_config"`
	PoolConfig       types.Object `tfsdk:"pool_config"`
	CreatedAt        types.String `tfsdk:"created_at"`
	UpdatedAt        types.String `tfsdk:"updated_at"`
	Password         types.String `tfsdk:"password"`
}

type cacheConfigModel struct {
	Enabled    types.Bool  `tfsdk:"enabled"`
	TTLSeconds types.Int64 `tfsdk:"ttl_seconds"`
	MaxEntries types.Int64 `tfsdk:"max_entries"`
	SWRSeconds types.Int64 `tfsdk:"swr_seconds"`
}

type poolConfigModel struct {
	PoolSize    types.Int64  `tfsdk:"pool_size"`
	MinPoolSize types.Int64  `tfsdk:"min_pool_size"`
	PoolMode    types.String `tfsdk:"pool_mode"`
	MaxActive   types.Int64  `tfsdk:"max_active"`
}

func NewDatabaseResource() resource.Resource {
	return &databaseResource{}
}

func cacheConfigAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"enabled":     types.BoolType,
		"ttl_seconds": types.Int64Type,
		"max_entries": types.Int64Type,
		"swr_seconds": types.Int64Type,
	}
}

func poolConfigAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"pool_size":     types.Int64Type,
		"min_pool_size": types.Int64Type,
		"pool_mode":     types.StringType,
		"max_active":    types.Int64Type,
	}
}

func (r *databaseResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_database"
}

func (r *databaseResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages an upstream database connection within a PgBeam project.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique database identifier (prefixed).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Description: "Owning project ID.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"connection_string": schema.StringAttribute{
				Description: "Connection string for connecting through PgBeam proxy. Password is replaced with a placeholder.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"host": schema.StringAttribute{
				Description: "PostgreSQL host.",
				Required:    true,
			},
			"port": schema.Int64Attribute{
				Description: "PostgreSQL port.",
				Required:    true,
			},
			"name": schema.StringAttribute{
				Description: "PostgreSQL database name.",
				Required:    true,
			},
			"username": schema.StringAttribute{
				Description: "PostgreSQL username.",
				Required:    true,
			},
			"ssl_mode": schema.StringAttribute{
				Description: "PostgreSQL SSL connection mode.",
				Optional:    true,
				Computed:    true,
			},
			"role": schema.StringAttribute{
				Description: "Database role. Primary receives writes, replicas receive reads.",
				Optional:    true,
			},
			"pool_region": schema.StringAttribute{
				Description: "Region where the connection pool is maintained (near the database). When set and different from the client's edge region, queries are relayed through the pool region's data plane. Empty means direct connection.\n",
				Optional:    true,
			},
			"query_timeout_ms": schema.Int64Attribute{
				Description: "Query timeout in milliseconds. When set (> 0), the proxy sends SET statement_timeout on upstream connections. 0 means disabled (default).\n",
				Optional:    true,
			},
			"auto_read_routing": schema.BoolAttribute{
				Description: "When enabled and replicas are configured, SELECT queries automatically route to read replicas without requiring the @pgbeam:replica SQL annotation.\n",
				Optional:    true,
			},
			"cache_config": schema.SingleNestedAttribute{
				Description: "Query cache configuration.",
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"enabled": schema.BoolAttribute{
						Description: "Whether query caching is enabled. When false, all queries bypass the cache.",
						Required:    true,
					},
					"ttl_seconds": schema.Int64Attribute{
						Description: "Cache TTL in seconds for query results.",
						Required:    true,
					},
					"max_entries": schema.Int64Attribute{
						Description: "Maximum number of cached query results.",
						Required:    true,
					},
					"swr_seconds": schema.Int64Attribute{
						Description: "Stale-while-revalidate window in seconds.",
						Required:    true,
					},
				},
			},
			"pool_config": schema.SingleNestedAttribute{
				Description: "Connection pool configuration.",
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"pool_size": schema.Int64Attribute{
						Description: "Maximum connections in the pool.",
						Required:    true,
					},
					"min_pool_size": schema.Int64Attribute{
						Description: "Minimum idle connections maintained.",
						Required:    true,
					},
					"pool_mode": schema.StringAttribute{
						Description: "Connection pool mode.",
						Required:    true,
					},
					"max_active": schema.Int64Attribute{
						Description: "Maximum concurrent upstream connections per pool.",
						Optional:    true,
					},
				},
			},
			"created_at": schema.StringAttribute{
				Description: "When the database registration was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the database registration was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"password": schema.StringAttribute{
				Description: "PostgreSQL password. Stored encrypted at rest.",
				Required:    true,
				Sensitive:   true,
			},
		},
	}
}

func (r *databaseResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *databaseResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan databaseResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	password := plan.Password.ValueString()
	createReq := pgbeam.CreateDatabaseRequest{
		Host:     plan.Host.ValueString(),
		Port:     int(plan.Port.ValueInt64()),
		Name:     plan.Name.ValueString(),
		Username: plan.Username.ValueString(),
		Password: &password,
	}

	if !plan.SSLMode.IsNull() && !plan.SSLMode.IsUnknown() {
		v := pgbeam.SSLMode(plan.SSLMode.ValueString())
		createReq.SslMode = &v
	}

	if !plan.Role.IsNull() && !plan.Role.IsUnknown() {
		v := pgbeam.DatabaseRole(plan.Role.ValueString())
		createReq.Role = &v
	}

	if !plan.PoolRegion.IsNull() && !plan.PoolRegion.IsUnknown() {
		v := plan.PoolRegion.ValueString()
		createReq.PoolRegion = &v
	}

	if !plan.QueryTimeoutMs.IsNull() && !plan.QueryTimeoutMs.IsUnknown() {
		v := int(plan.QueryTimeoutMs.ValueInt64())
		createReq.QueryTimeoutMs = &v
	}

	if !plan.AutoReadRouting.IsNull() && !plan.AutoReadRouting.IsUnknown() {
		v := plan.AutoReadRouting.ValueBool()
		createReq.AutoReadRouting = &v
	}

	if !plan.CacheConfig.IsNull() && !plan.CacheConfig.IsUnknown() {
		var cacheConfigVar cacheConfigModel
		resp.Diagnostics.Append(plan.CacheConfig.As(ctx, &cacheConfigVar, objectAsOptions())...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.CacheConfig = &pgbeam.CacheConfig{
			Enabled:    cacheConfigVar.Enabled.ValueBool(),
			TtlSeconds: int(cacheConfigVar.TTLSeconds.ValueInt64()),
			MaxEntries: int(cacheConfigVar.MaxEntries.ValueInt64()),
			SwrSeconds: int(cacheConfigVar.SWRSeconds.ValueInt64()),
		}
	}

	if !plan.PoolConfig.IsNull() && !plan.PoolConfig.IsUnknown() {
		var poolConfigVar poolConfigModel
		resp.Diagnostics.Append(plan.PoolConfig.As(ctx, &poolConfigVar, objectAsOptions())...)
		if resp.Diagnostics.HasError() {
			return
		}
		tmpPoolConfigMaxActive := int(poolConfigVar.MaxActive.ValueInt64())
		createReq.PoolConfig = &pgbeam.PoolConfig{
			PoolSize:    int(poolConfigVar.PoolSize.ValueInt64()),
			MinPoolSize: int(poolConfigVar.MinPoolSize.ValueInt64()),
			PoolMode:    pgbeam.PoolMode(poolConfigVar.PoolMode.ValueString()),
			MaxActive:   &tmpPoolConfigMaxActive,
		}
	}

	result, err := r.client.Databases.CreateDatabase(ctx, plan.ProjectID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating database", err.Error())
		return
	}

	plan.ID = types.StringValue(result.Id)
	r.mapDatabaseToState(ctx, &plan, result, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *databaseResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state databaseResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	Database, err := r.client.Databases.GetDatabase(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading database", err.Error())
		return
	}

	r.mapDatabaseToState(ctx, &state, Database, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *databaseResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan databaseResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state databaseResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateReq := pgbeam.UpdateDatabaseRequest{}
	hasChanges := false

	if !plan.Host.Equal(state.Host) {
		v := plan.Host.ValueString()
		updateReq.Host = &v
		hasChanges = true
	}

	if !plan.Port.Equal(state.Port) {
		v := int(plan.Port.ValueInt64())
		updateReq.Port = &v
		hasChanges = true
	}

	if !plan.Name.Equal(state.Name) {
		v := plan.Name.ValueString()
		updateReq.Name = &v
		hasChanges = true
	}

	if !plan.Username.Equal(state.Username) {
		v := plan.Username.ValueString()
		updateReq.Username = &v
		hasChanges = true
	}

	if !plan.SSLMode.Equal(state.SSLMode) {
		v := pgbeam.SSLMode(plan.SSLMode.ValueString())
		updateReq.SslMode = &v
		hasChanges = true
	}

	if !plan.Role.Equal(state.Role) {
		v := pgbeam.DatabaseRole(plan.Role.ValueString())
		updateReq.Role = &v
		hasChanges = true
	}

	if !plan.PoolRegion.Equal(state.PoolRegion) {
		v := plan.PoolRegion.ValueString()
		updateReq.PoolRegion = &v
		hasChanges = true
	}

	if !plan.QueryTimeoutMs.Equal(state.QueryTimeoutMs) {
		v := int(plan.QueryTimeoutMs.ValueInt64())
		updateReq.QueryTimeoutMs = &v
		hasChanges = true
	}

	if !plan.AutoReadRouting.Equal(state.AutoReadRouting) {
		v := plan.AutoReadRouting.ValueBool()
		updateReq.AutoReadRouting = &v
		hasChanges = true
	}

	if !plan.Password.Equal(state.Password) {
		v := plan.Password.ValueString()
		updateReq.Password = &v
		hasChanges = true
	}

	if !plan.CacheConfig.Equal(state.CacheConfig) {
		if !plan.CacheConfig.IsNull() && !plan.CacheConfig.IsUnknown() {
			var cacheConfigVar cacheConfigModel
			resp.Diagnostics.Append(plan.CacheConfig.As(ctx, &cacheConfigVar, objectAsOptions())...)
			if resp.Diagnostics.HasError() {
				return
			}
			updateReq.CacheConfig = &pgbeam.CacheConfig{
				Enabled:    cacheConfigVar.Enabled.ValueBool(),
				TtlSeconds: int(cacheConfigVar.TTLSeconds.ValueInt64()),
				MaxEntries: int(cacheConfigVar.MaxEntries.ValueInt64()),
				SwrSeconds: int(cacheConfigVar.SWRSeconds.ValueInt64()),
			}
			hasChanges = true
		}
	}

	if !plan.PoolConfig.Equal(state.PoolConfig) {
		if !plan.PoolConfig.IsNull() && !plan.PoolConfig.IsUnknown() {
			var poolConfigVar poolConfigModel
			resp.Diagnostics.Append(plan.PoolConfig.As(ctx, &poolConfigVar, objectAsOptions())...)
			if resp.Diagnostics.HasError() {
				return
			}
			tmpPoolConfigMaxActive := int(poolConfigVar.MaxActive.ValueInt64())
			updateReq.PoolConfig = &pgbeam.PoolConfig{
				PoolSize:    int(poolConfigVar.PoolSize.ValueInt64()),
				MinPoolSize: int(poolConfigVar.MinPoolSize.ValueInt64()),
				PoolMode:    pgbeam.PoolMode(poolConfigVar.PoolMode.ValueString()),
				MaxActive:   &tmpPoolConfigMaxActive,
			}
			hasChanges = true
		}
	}

	if hasChanges {
		_, err := r.client.Databases.UpdateDatabase(ctx, state.ProjectID.ValueString(), state.ID.ValueString(), updateReq)
		if err != nil {
			resp.Diagnostics.AddError("Error updating database", err.Error())
			return
		}
	}

	Database, err := r.client.Databases.GetDatabase(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading database after update", err.Error())
		return
	}

	plan.ID = state.ID
	r.mapDatabaseToState(ctx, &plan, Database, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *databaseResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state databaseResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Databases.DeleteDatabase(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting database", err.Error())
	}
}

func (r *databaseResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: project_id/database_id")
		return
	}

	projectID := parts[0]
	databaseID := parts[1]

	Database, err := r.client.Databases.GetDatabase(ctx, projectID, databaseID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing database", err.Error())
		return
	}

	var state databaseResourceModel
	state.ID = types.StringValue(Database.Id)
	state.ProjectID = types.StringValue(projectID)
	// Password cannot be read back from API
	state.Password = types.StringValue("")
	r.mapDatabaseToState(ctx, &state, Database, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *databaseResource) mapDatabaseToState(ctx context.Context, state *databaseResourceModel, resp *pgbeam.Database, diags *diag.Diagnostics) {
	state.ProjectID = types.StringValue(resp.ProjectId)
	if resp.ConnectionString != nil {
		state.ConnectionString = types.StringValue(*resp.ConnectionString)
	} else {
		state.ConnectionString = types.StringNull()
	}
	state.Host = types.StringValue(resp.Host)
	state.Port = types.Int64Value(int64(resp.Port))
	state.Name = types.StringValue(resp.Name)
	state.Username = types.StringValue(resp.Username)
	if string(resp.SslMode) != "" {
		state.SSLMode = types.StringValue(string(resp.SslMode))
	} else {
		state.SSLMode = types.StringNull()
	}
	if resp.Role != nil && string(*resp.Role) != "" {
		state.Role = types.StringValue(string(*resp.Role))
	} else {
		state.Role = types.StringNull()
	}
	if resp.PoolRegion != nil {
		state.PoolRegion = types.StringValue(*resp.PoolRegion)
	} else {
		state.PoolRegion = types.StringNull()
	}
	if resp.QueryTimeoutMs != nil {
		state.QueryTimeoutMs = types.Int64Value(int64(*resp.QueryTimeoutMs))
	} else {
		state.QueryTimeoutMs = types.Int64Null()
	}
	if resp.AutoReadRouting != nil {
		state.AutoReadRouting = types.BoolValue(*resp.AutoReadRouting)
	} else {
		state.AutoReadRouting = types.BoolNull()
	}
	obj, d := types.ObjectValue(cacheConfigAttrTypes(), map[string]attr.Value{
		"enabled":     types.BoolValue(resp.CacheConfig.Enabled),
		"ttl_seconds": types.Int64Value(int64(resp.CacheConfig.TtlSeconds)),
		"max_entries": types.Int64Value(int64(resp.CacheConfig.MaxEntries)),
		"swr_seconds": types.Int64Value(int64(resp.CacheConfig.SwrSeconds)),
	})
	diags.Append(d...)
	state.CacheConfig = obj
	poolConfigObj, poolConfigD := types.ObjectValue(poolConfigAttrTypes(), map[string]attr.Value{
		"pool_size":     types.Int64Value(int64(resp.PoolConfig.PoolSize)),
		"min_pool_size": types.Int64Value(int64(resp.PoolConfig.MinPoolSize)),
		"pool_mode":     types.StringValue(string(resp.PoolConfig.PoolMode)),
		"max_active":    types.Int64Value(int64(*resp.PoolConfig.MaxActive)),
	})
	diags.Append(poolConfigD...)
	state.PoolConfig = poolConfigObj
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
