// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*policyProfileResource)(nil)
	_ resource.ResourceWithConfigure   = (*policyProfileResource)(nil)
	_ resource.ResourceWithImportState = (*policyProfileResource)(nil)
)

type policyProfileResource struct {
	client *pgbeam.Client
}

type policyProfileResourceModel struct {
	ID                     types.String `tfsdk:"id"`
	ProjectID              types.String `tfsdk:"project_id"`
	Name                   types.String `tfsdk:"name"`
	AccessMode             types.String `tfsdk:"access_mode"`
	StatementRules         types.Object `tfsdk:"statement_rules"`
	TableAllowlist         types.List   `tfsdk:"table_allowlist"`
	TableDenylist          types.List   `tfsdk:"table_denylist"`
	MaskingRules           types.List   `tfsdk:"masking_rules"`
	BudgetQueriesPerHour   types.Int64  `tfsdk:"budget_queries_per_hour"`
	BudgetQueriesPerDay    types.Int64  `tfsdk:"budget_queries_per_day"`
	MaxRows                types.Int64  `tfsdk:"max_rows"`
	StatementTimeoutMs     types.Int64  `tfsdk:"statement_timeout_ms"`
	RowFilters             types.List   `tfsdk:"row_filters"`
	WriteMode              types.String `tfsdk:"write_mode"`
	ApprovalMode           types.String `tfsdk:"approval_mode"`
	ApprovalAutoMaxRows    types.Int64  `tfsdk:"approval_auto_max_rows"`
	ApprovalTimeoutSeconds types.Int64  `tfsdk:"approval_timeout_seconds"`
	MigrationSafety        types.String `tfsdk:"migration_safety"`
	EgressBytesPerDay      types.Int64  `tfsdk:"egress_bytes_per_day"`
	MaxAffectedRows        types.Int64  `tfsdk:"max_affected_rows"`
	ContentScanMode        types.String `tfsdk:"content_scan_mode"`
	ContentScanMaxBytes    types.Int64  `tfsdk:"content_scan_max_bytes"`
	CreatedAt              types.String `tfsdk:"created_at"`
	UpdatedAt              types.String `tfsdk:"updated_at"`
}

type statementRulesModel struct {
	Allow types.List `tfsdk:"allow"`
	Deny  types.List `tfsdk:"deny"`
}

type maskingRulesElemModel struct {
	Table  types.String `tfsdk:"table"`
	Column types.String `tfsdk:"column"`
	Kind   types.String `tfsdk:"kind"`
}

type rowFiltersElemModel struct {
	Table     types.String `tfsdk:"table"`
	Predicate types.String `tfsdk:"predicate"`
}

func NewPolicyProfileResource() resource.Resource {
	return &policyProfileResource{}
}

func statementRulesAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"allow": types.ListType{ElemType: types.StringType},
		"deny":  types.ListType{ElemType: types.StringType},
	}
}

func maskingRulesElemAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"table":  types.StringType,
		"column": types.StringType,
		"kind":   types.StringType,
	}
}

func rowFiltersElemAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"table":     types.StringType,
		"predicate": types.StringType,
	}
}

func (r *policyProfileResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_policy_profile"
}

func (r *policyProfileResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a policy profile: a named bundle of agent-gateway enforcement rules (access mode, table allow/deny lists, statement-kind rules, PII masking rules, per-relation row filters, query/egress budgets, write mode, approvals, and migration safety) attached to agent credentials and enforced in the PG wire protocol. Nested-list fields (masking_rules, row_filters) and the nested statement_rules object are expressed as structured config.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique policy profile identifier (prefixed).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Description: "Owning project ID.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Human-readable name for the policy profile.",
				Required:    true,
			},
			"access_mode": schema.StringAttribute{
				Description: "read_only blocks all data and schema mutations.",
				Optional:    true,
			},
			"statement_rules": schema.SingleNestedAttribute{
				Description: "Per-statement-kind allow/deny lists. Empty allow means all kinds permitted by the access mode.",
				Optional:    true,
				Attributes: map[string]schema.Attribute{
					"allow": schema.ListAttribute{
						Description: "Allowed statement kinds (select, insert, update, delete, ddl, copy, set, show, explain, transaction).",
						Optional:    true,
						ElementType: types.StringType,
					},
					"deny": schema.ListAttribute{
						Description: "Denied statement kinds (takes precedence over allow).",
						Optional:    true,
						ElementType: types.StringType,
					},
				},
			},
			"table_allowlist": schema.ListAttribute{
				Description: "If non-empty, only these relations are reachable. Entries are schema-qualified (billing.orders) or bare (orders); a bare entry grants the public schema only, so the same table name in another schema must be listed in full.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"table_denylist": schema.ListAttribute{
				Description: "Relations explicitly blocked (takes precedence over the allowlist). A bare entry blocks that relation in every schema.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"masking_rules": schema.ListNestedAttribute{
				Description: "Column masking rules applied to query results.",
				Optional:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"table": schema.StringAttribute{
							Description: "Relation name, optionally schema-qualified (e.g. \"public.users\" or \"users\").",
							Required:    true,
						},
						"column": schema.StringAttribute{
							Description: "Column to mask.",
							Required:    true,
						},
						"kind": schema.StringAttribute{
							Description: "How to mask. redact replaces with a token, null returns NULL, hash returns a SHA-256 hex.",
							Required:    true,
						},
					},
				},
			},
			"budget_queries_per_hour": schema.Int64Attribute{
				Description: "Max queries per rolling hour window. 0 means unlimited.",
				Optional:    true,
			},
			"budget_queries_per_day": schema.Int64Attribute{
				Description: "Max queries per day window. 0 means unlimited.",
				Optional:    true,
			},
			"max_rows": schema.Int64Attribute{
				Description: "Max rows returned per query. 0 means unlimited.",
				Optional:    true,
			},
			"statement_timeout_ms": schema.Int64Attribute{
				Description: "Upstream statement timeout for agent sessions. 0 uses the project default.",
				Optional:    true,
			},
			"row_filters": schema.ListNestedAttribute{
				Description: "Per-relation row filters ANDed into agent reads.",
				Optional:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"table": schema.StringAttribute{
							Description: "Relation name, optionally schema-qualified (e.g. \"public.orders\").",
							Required:    true,
						},
						"predicate": schema.StringAttribute{
							Description: "Raw SQL boolean expression ANDed into WHERE for this relation.",
							Required:    true,
						},
					},
				},
			},
			"write_mode": schema.StringAttribute{
				Description: "How writes are handled. normal commits, rollback auto-rolls back, sandbox routes to an ephemeral branch.",
				Optional:    true,
			},
			"approval_mode": schema.StringAttribute{
				Description: "Which statement classes require human approval before execution.",
				Optional:    true,
			},
			"approval_auto_max_rows": schema.Int64Attribute{
				Description: "Statements touching at most this many rows are auto-approved. 0 means none.",
				Optional:    true,
			},
			"approval_timeout_seconds": schema.Int64Attribute{
				Description: "How long a held statement waits for a decision before expiring.",
				Optional:    true,
			},
			"migration_safety": schema.StringAttribute{
				Description: "Migration safety mode. warn surfaces findings, block refuses unsafe DDL.",
				Optional:    true,
			},
			"egress_bytes_per_day": schema.Int64Attribute{
				Description: "Per-day egress budget in bytes. 0 means unlimited.",
				Optional:    true,
			},
			"max_affected_rows": schema.Int64Attribute{
				Description: "Hard cap on rows a single write (INSERT/UPDATE/DELETE) may affect. A write whose affected-row count would exceed this is executed inside a transaction, checked, and rolled back so nothing persists, then blocked. Enforced independently of human approval. 0 means unlimited.",
				Optional:    true,
			},
			"content_scan_mode": schema.StringAttribute{
				Description: "Result-content scanning, accepted and stored but not yet enforced: no released proxy build reads this field, so today every value behaves like off. Once enforcement ships on the data-plane relay path, values on their way out to an agent will be checked for instruction-shaped content (stored prompt injection). off will scan nothing and cost nothing. annotate will forward every value unchanged and record what it found. block will additionally refuse the statement with an error naming the column, and never drop a row silently. A proxy build without result-content scanning ignores this field.",
				Optional:    true,
			},
			"content_scan_max_bytes": schema.Int64Attribute{
				Description: "Byte budget for one statement's content scan, spanning all values in the result. Stored but not yet read by any released proxy build, like content_scan_mode. Once enforced, values past it are reported unscannable rather than skipped quietly. 0 uses the scanner default (4 MiB), which covers an interactive result set and deliberately does not cover a bulk export.",
				Optional:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "When the policy profile was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the policy profile was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *policyProfileResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *policyProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan policyProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.PolicyProfileInput{
		Name: plan.Name.ValueString(),
	}

	if !plan.AccessMode.IsNull() && !plan.AccessMode.IsUnknown() {
		v := pgbeam.PolicyProfileInputAccessMode(plan.AccessMode.ValueString())
		createReq.AccessMode = &v
	}

	if !plan.TableAllowlist.IsNull() && !plan.TableAllowlist.IsUnknown() {
		var v []string
		resp.Diagnostics.Append(plan.TableAllowlist.ElementsAs(ctx, &v, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.TableAllowlist = &v
	}

	if !plan.TableDenylist.IsNull() && !plan.TableDenylist.IsUnknown() {
		var v []string
		resp.Diagnostics.Append(plan.TableDenylist.ElementsAs(ctx, &v, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.TableDenylist = &v
	}

	if !plan.MaskingRules.IsNull() && !plan.MaskingRules.IsUnknown() {
		var maskingRulesElems []maskingRulesElemModel
		resp.Diagnostics.Append(plan.MaskingRules.ElementsAs(ctx, &maskingRulesElems, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		maskingRulesEntries := make([]pgbeam.MaskingRule, len(maskingRulesElems))
		for i, e := range maskingRulesElems {
			maskingRulesEntries[i] = pgbeam.MaskingRule{
				Table:  e.Table.ValueString(),
				Column: e.Column.ValueString(),
				Kind:   pgbeam.MaskingRuleKind(e.Kind.ValueString()),
			}
		}
		createReq.MaskingRules = &maskingRulesEntries
	}

	if !plan.BudgetQueriesPerHour.IsNull() && !plan.BudgetQueriesPerHour.IsUnknown() {
		v := int(plan.BudgetQueriesPerHour.ValueInt64())
		createReq.BudgetQueriesPerHour = &v
	}

	if !plan.BudgetQueriesPerDay.IsNull() && !plan.BudgetQueriesPerDay.IsUnknown() {
		v := int(plan.BudgetQueriesPerDay.ValueInt64())
		createReq.BudgetQueriesPerDay = &v
	}

	if !plan.MaxRows.IsNull() && !plan.MaxRows.IsUnknown() {
		v := int(plan.MaxRows.ValueInt64())
		createReq.MaxRows = &v
	}

	if !plan.StatementTimeoutMs.IsNull() && !plan.StatementTimeoutMs.IsUnknown() {
		v := int(plan.StatementTimeoutMs.ValueInt64())
		createReq.StatementTimeoutMs = &v
	}

	if !plan.RowFilters.IsNull() && !plan.RowFilters.IsUnknown() {
		var rowFiltersElems []rowFiltersElemModel
		resp.Diagnostics.Append(plan.RowFilters.ElementsAs(ctx, &rowFiltersElems, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		rowFiltersEntries := make([]pgbeam.RowFilter, len(rowFiltersElems))
		for i, e := range rowFiltersElems {
			rowFiltersEntries[i] = pgbeam.RowFilter{
				Table:     e.Table.ValueString(),
				Predicate: e.Predicate.ValueString(),
			}
		}
		createReq.RowFilters = &rowFiltersEntries
	}

	if !plan.WriteMode.IsNull() && !plan.WriteMode.IsUnknown() {
		v := pgbeam.PolicyProfileInputWriteMode(plan.WriteMode.ValueString())
		createReq.WriteMode = &v
	}

	if !plan.ApprovalMode.IsNull() && !plan.ApprovalMode.IsUnknown() {
		v := pgbeam.PolicyProfileInputApprovalMode(plan.ApprovalMode.ValueString())
		createReq.ApprovalMode = &v
	}

	if !plan.ApprovalAutoMaxRows.IsNull() && !plan.ApprovalAutoMaxRows.IsUnknown() {
		v := int(plan.ApprovalAutoMaxRows.ValueInt64())
		createReq.ApprovalAutoMaxRows = &v
	}

	if !plan.ApprovalTimeoutSeconds.IsNull() && !plan.ApprovalTimeoutSeconds.IsUnknown() {
		v := int(plan.ApprovalTimeoutSeconds.ValueInt64())
		createReq.ApprovalTimeoutSeconds = &v
	}

	if !plan.MigrationSafety.IsNull() && !plan.MigrationSafety.IsUnknown() {
		v := pgbeam.PolicyProfileInputMigrationSafety(plan.MigrationSafety.ValueString())
		createReq.MigrationSafety = &v
	}

	if !plan.EgressBytesPerDay.IsNull() && !plan.EgressBytesPerDay.IsUnknown() {
		v := plan.EgressBytesPerDay.ValueInt64()
		createReq.EgressBytesPerDay = &v
	}

	if !plan.MaxAffectedRows.IsNull() && !plan.MaxAffectedRows.IsUnknown() {
		v := int(plan.MaxAffectedRows.ValueInt64())
		createReq.MaxAffectedRows = &v
	}

	if !plan.ContentScanMode.IsNull() && !plan.ContentScanMode.IsUnknown() {
		v := pgbeam.PolicyProfileInputContentScanMode(plan.ContentScanMode.ValueString())
		createReq.ContentScanMode = &v
	}

	if !plan.ContentScanMaxBytes.IsNull() && !plan.ContentScanMaxBytes.IsUnknown() {
		v := plan.ContentScanMaxBytes.ValueInt64()
		createReq.ContentScanMaxBytes = &v
	}

	if !plan.StatementRules.IsNull() && !plan.StatementRules.IsUnknown() {
		var statementRulesVar statementRulesModel
		resp.Diagnostics.Append(plan.StatementRules.As(ctx, &statementRulesVar, objectAsOptions())...)
		if resp.Diagnostics.HasError() {
			return
		}
		var statementRulesAllow []string
		if !statementRulesVar.Allow.IsNull() && !statementRulesVar.Allow.IsUnknown() {
			resp.Diagnostics.Append(statementRulesVar.Allow.ElementsAs(ctx, &statementRulesAllow, false)...)
			if resp.Diagnostics.HasError() {
				return
			}
		}
		var statementRulesDeny []string
		if !statementRulesVar.Deny.IsNull() && !statementRulesVar.Deny.IsUnknown() {
			resp.Diagnostics.Append(statementRulesVar.Deny.ElementsAs(ctx, &statementRulesDeny, false)...)
			if resp.Diagnostics.HasError() {
				return
			}
		}
		createReq.StatementRules = &pgbeam.StatementRules{
			Allow: &statementRulesAllow,
			Deny:  &statementRulesDeny,
		}
	}

	result, err := r.client.Policies.CreatePolicyProfile(ctx, plan.ProjectID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating policy profile", err.Error())
		return
	}

	plan.ID = types.StringValue(result.Id)
	r.mapPolicyProfileToState(ctx, &plan, result, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *policyProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state policyProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	PolicyProfile, err := r.client.Policies.GetPolicyProfile(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading policy profile", err.Error())
		return
	}

	r.mapPolicyProfileToState(ctx, &state, PolicyProfile, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *policyProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan policyProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state policyProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	hasChanges := !plan.Name.Equal(state.Name) ||
		!plan.AccessMode.Equal(state.AccessMode) ||
		!plan.TableAllowlist.Equal(state.TableAllowlist) ||
		!plan.TableDenylist.Equal(state.TableDenylist) ||
		!plan.MaskingRules.Equal(state.MaskingRules) ||
		!plan.BudgetQueriesPerHour.Equal(state.BudgetQueriesPerHour) ||
		!plan.BudgetQueriesPerDay.Equal(state.BudgetQueriesPerDay) ||
		!plan.MaxRows.Equal(state.MaxRows) ||
		!plan.StatementTimeoutMs.Equal(state.StatementTimeoutMs) ||
		!plan.RowFilters.Equal(state.RowFilters) ||
		!plan.WriteMode.Equal(state.WriteMode) ||
		!plan.ApprovalMode.Equal(state.ApprovalMode) ||
		!plan.ApprovalAutoMaxRows.Equal(state.ApprovalAutoMaxRows) ||
		!plan.ApprovalTimeoutSeconds.Equal(state.ApprovalTimeoutSeconds) ||
		!plan.MigrationSafety.Equal(state.MigrationSafety) ||
		!plan.EgressBytesPerDay.Equal(state.EgressBytesPerDay) ||
		!plan.MaxAffectedRows.Equal(state.MaxAffectedRows) ||
		!plan.ContentScanMode.Equal(state.ContentScanMode) ||
		!plan.ContentScanMaxBytes.Equal(state.ContentScanMaxBytes) ||
		!plan.StatementRules.Equal(state.StatementRules)

	updateReq := pgbeam.PolicyProfileInput{
		Name: plan.Name.ValueString(),
	}

	if !plan.AccessMode.IsNull() && !plan.AccessMode.IsUnknown() {
		v := pgbeam.PolicyProfileInputAccessMode(plan.AccessMode.ValueString())
		updateReq.AccessMode = &v
	}

	if !plan.TableAllowlist.IsNull() && !plan.TableAllowlist.IsUnknown() {
		var v []string
		resp.Diagnostics.Append(plan.TableAllowlist.ElementsAs(ctx, &v, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		updateReq.TableAllowlist = &v
	}

	if !plan.TableDenylist.IsNull() && !plan.TableDenylist.IsUnknown() {
		var v []string
		resp.Diagnostics.Append(plan.TableDenylist.ElementsAs(ctx, &v, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		updateReq.TableDenylist = &v
	}

	if !plan.MaskingRules.IsNull() && !plan.MaskingRules.IsUnknown() {
		var maskingRulesElems []maskingRulesElemModel
		resp.Diagnostics.Append(plan.MaskingRules.ElementsAs(ctx, &maskingRulesElems, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		maskingRulesEntries := make([]pgbeam.MaskingRule, len(maskingRulesElems))
		for i, e := range maskingRulesElems {
			maskingRulesEntries[i] = pgbeam.MaskingRule{
				Table:  e.Table.ValueString(),
				Column: e.Column.ValueString(),
				Kind:   pgbeam.MaskingRuleKind(e.Kind.ValueString()),
			}
		}
		updateReq.MaskingRules = &maskingRulesEntries
	}

	if !plan.BudgetQueriesPerHour.IsNull() && !plan.BudgetQueriesPerHour.IsUnknown() {
		v := int(plan.BudgetQueriesPerHour.ValueInt64())
		updateReq.BudgetQueriesPerHour = &v
	}

	if !plan.BudgetQueriesPerDay.IsNull() && !plan.BudgetQueriesPerDay.IsUnknown() {
		v := int(plan.BudgetQueriesPerDay.ValueInt64())
		updateReq.BudgetQueriesPerDay = &v
	}

	if !plan.MaxRows.IsNull() && !plan.MaxRows.IsUnknown() {
		v := int(plan.MaxRows.ValueInt64())
		updateReq.MaxRows = &v
	}

	if !plan.StatementTimeoutMs.IsNull() && !plan.StatementTimeoutMs.IsUnknown() {
		v := int(plan.StatementTimeoutMs.ValueInt64())
		updateReq.StatementTimeoutMs = &v
	}

	if !plan.RowFilters.IsNull() && !plan.RowFilters.IsUnknown() {
		var rowFiltersElems []rowFiltersElemModel
		resp.Diagnostics.Append(plan.RowFilters.ElementsAs(ctx, &rowFiltersElems, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		rowFiltersEntries := make([]pgbeam.RowFilter, len(rowFiltersElems))
		for i, e := range rowFiltersElems {
			rowFiltersEntries[i] = pgbeam.RowFilter{
				Table:     e.Table.ValueString(),
				Predicate: e.Predicate.ValueString(),
			}
		}
		updateReq.RowFilters = &rowFiltersEntries
	}

	if !plan.WriteMode.IsNull() && !plan.WriteMode.IsUnknown() {
		v := pgbeam.PolicyProfileInputWriteMode(plan.WriteMode.ValueString())
		updateReq.WriteMode = &v
	}

	if !plan.ApprovalMode.IsNull() && !plan.ApprovalMode.IsUnknown() {
		v := pgbeam.PolicyProfileInputApprovalMode(plan.ApprovalMode.ValueString())
		updateReq.ApprovalMode = &v
	}

	if !plan.ApprovalAutoMaxRows.IsNull() && !plan.ApprovalAutoMaxRows.IsUnknown() {
		v := int(plan.ApprovalAutoMaxRows.ValueInt64())
		updateReq.ApprovalAutoMaxRows = &v
	}

	if !plan.ApprovalTimeoutSeconds.IsNull() && !plan.ApprovalTimeoutSeconds.IsUnknown() {
		v := int(plan.ApprovalTimeoutSeconds.ValueInt64())
		updateReq.ApprovalTimeoutSeconds = &v
	}

	if !plan.MigrationSafety.IsNull() && !plan.MigrationSafety.IsUnknown() {
		v := pgbeam.PolicyProfileInputMigrationSafety(plan.MigrationSafety.ValueString())
		updateReq.MigrationSafety = &v
	}

	if !plan.EgressBytesPerDay.IsNull() && !plan.EgressBytesPerDay.IsUnknown() {
		v := plan.EgressBytesPerDay.ValueInt64()
		updateReq.EgressBytesPerDay = &v
	}

	if !plan.MaxAffectedRows.IsNull() && !plan.MaxAffectedRows.IsUnknown() {
		v := int(plan.MaxAffectedRows.ValueInt64())
		updateReq.MaxAffectedRows = &v
	}

	if !plan.ContentScanMode.IsNull() && !plan.ContentScanMode.IsUnknown() {
		v := pgbeam.PolicyProfileInputContentScanMode(plan.ContentScanMode.ValueString())
		updateReq.ContentScanMode = &v
	}

	if !plan.ContentScanMaxBytes.IsNull() && !plan.ContentScanMaxBytes.IsUnknown() {
		v := plan.ContentScanMaxBytes.ValueInt64()
		updateReq.ContentScanMaxBytes = &v
	}

	if !plan.StatementRules.IsNull() && !plan.StatementRules.IsUnknown() {
		var statementRulesVar statementRulesModel
		resp.Diagnostics.Append(plan.StatementRules.As(ctx, &statementRulesVar, objectAsOptions())...)
		if resp.Diagnostics.HasError() {
			return
		}
		var statementRulesAllow []string
		if !statementRulesVar.Allow.IsNull() && !statementRulesVar.Allow.IsUnknown() {
			resp.Diagnostics.Append(statementRulesVar.Allow.ElementsAs(ctx, &statementRulesAllow, false)...)
			if resp.Diagnostics.HasError() {
				return
			}
		}
		var statementRulesDeny []string
		if !statementRulesVar.Deny.IsNull() && !statementRulesVar.Deny.IsUnknown() {
			resp.Diagnostics.Append(statementRulesVar.Deny.ElementsAs(ctx, &statementRulesDeny, false)...)
			if resp.Diagnostics.HasError() {
				return
			}
		}
		updateReq.StatementRules = &pgbeam.StatementRules{
			Allow: &statementRulesAllow,
			Deny:  &statementRulesDeny,
		}
	}

	if hasChanges {
		_, err := r.client.Policies.UpdatePolicyProfile(ctx, state.ProjectID.ValueString(), state.ID.ValueString(), updateReq)
		if err != nil {
			resp.Diagnostics.AddError("Error updating policy profile", err.Error())
			return
		}
	}

	PolicyProfile, err := r.client.Policies.GetPolicyProfile(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading policy profile after update", err.Error())
		return
	}

	plan.ID = state.ID
	r.mapPolicyProfileToState(ctx, &plan, PolicyProfile, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *policyProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state policyProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Policies.DeletePolicyProfile(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting policy profile", err.Error())
	}
}

func (r *policyProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: project_id/policy_id")
		return
	}

	projectID := parts[0]
	policyID := parts[1]

	PolicyProfile, err := r.client.Policies.GetPolicyProfile(ctx, projectID, policyID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing policy profile", err.Error())
		return
	}

	var state policyProfileResourceModel
	state.ID = types.StringValue(PolicyProfile.Id)
	state.ProjectID = types.StringValue(projectID)
	r.mapPolicyProfileToState(ctx, &state, PolicyProfile, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *policyProfileResource) mapPolicyProfileToState(ctx context.Context, state *policyProfileResourceModel, resp *pgbeam.PolicyProfile, diags *diag.Diagnostics) {
	state.ProjectID = types.StringValue(resp.ProjectId)
	state.Name = types.StringValue(resp.Name)
	if string(resp.AccessMode) != "" {
		state.AccessMode = types.StringValue(string(resp.AccessMode))
	} else {
		state.AccessMode = types.StringNull()
	}
	if resp.StatementRules != nil {
		statementRulesAllowList := types.ListNull(types.StringType)
		if resp.StatementRules.Allow != nil {
			lv, lvD := types.ListValueFrom(ctx, types.StringType, *resp.StatementRules.Allow)
			diags.Append(lvD...)
			statementRulesAllowList = lv
		}
		statementRulesDenyList := types.ListNull(types.StringType)
		if resp.StatementRules.Deny != nil {
			lv, lvD := types.ListValueFrom(ctx, types.StringType, *resp.StatementRules.Deny)
			diags.Append(lvD...)
			statementRulesDenyList = lv
		}
		obj, d := types.ObjectValue(statementRulesAttrTypes(), map[string]attr.Value{
			"allow": statementRulesAllowList,
			"deny":  statementRulesDenyList,
		})
		diags.Append(d...)
		state.StatementRules = obj
	} else {
		state.StatementRules = types.ObjectNull(statementRulesAttrTypes())
	}
	if len(resp.TableAllowlist) > 0 {
		tagValues := make([]attr.Value, len(resp.TableAllowlist))
		for i, t := range resp.TableAllowlist {
			tagValues[i] = types.StringValue(t)
		}
		tagsList, d := types.ListValue(types.StringType, tagValues)
		diags.Append(d...)
		state.TableAllowlist = tagsList
	} else {
		state.TableAllowlist = types.ListNull(types.StringType)
	}
	if len(resp.TableDenylist) > 0 {
		tagValues := make([]attr.Value, len(resp.TableDenylist))
		for i, t := range resp.TableDenylist {
			tagValues[i] = types.StringValue(t)
		}
		tagsList, d := types.ListValue(types.StringType, tagValues)
		diags.Append(d...)
		state.TableDenylist = tagsList
	} else {
		state.TableDenylist = types.ListNull(types.StringType)
	}
	if len(resp.MaskingRules) > 0 {
		maskingRulesValues := make([]attr.Value, len(resp.MaskingRules))
		for i, e := range resp.MaskingRules {
			maskingRulesValues[i] = types.ObjectValueMust(maskingRulesElemAttrTypes(), map[string]attr.Value{
				"table":  types.StringValue(e.Table),
				"column": types.StringValue(e.Column),
				"kind":   types.StringValue(string(e.Kind)),
			})
		}
		maskingRulesList, maskingRulesD := types.ListValue(types.ObjectType{AttrTypes: maskingRulesElemAttrTypes()}, maskingRulesValues)
		diags.Append(maskingRulesD...)
		state.MaskingRules = maskingRulesList
	} else {
		state.MaskingRules = types.ListNull(types.ObjectType{AttrTypes: maskingRulesElemAttrTypes()})
	}
	if resp.BudgetQueriesPerHour != nil {
		state.BudgetQueriesPerHour = types.Int64Value(int64(*resp.BudgetQueriesPerHour))
	} else {
		state.BudgetQueriesPerHour = types.Int64Null()
	}
	if resp.BudgetQueriesPerDay != nil {
		state.BudgetQueriesPerDay = types.Int64Value(int64(*resp.BudgetQueriesPerDay))
	} else {
		state.BudgetQueriesPerDay = types.Int64Null()
	}
	if resp.MaxRows != nil {
		state.MaxRows = types.Int64Value(int64(*resp.MaxRows))
	} else {
		state.MaxRows = types.Int64Null()
	}
	if resp.StatementTimeoutMs != nil {
		state.StatementTimeoutMs = types.Int64Value(int64(*resp.StatementTimeoutMs))
	} else {
		state.StatementTimeoutMs = types.Int64Null()
	}
	if resp.RowFilters != nil && len(*resp.RowFilters) > 0 {
		rowFiltersValues := make([]attr.Value, len(*resp.RowFilters))
		for i, e := range *resp.RowFilters {
			rowFiltersValues[i] = types.ObjectValueMust(rowFiltersElemAttrTypes(), map[string]attr.Value{
				"table":     types.StringValue(e.Table),
				"predicate": types.StringValue(e.Predicate),
			})
		}
		rowFiltersList, rowFiltersD := types.ListValue(types.ObjectType{AttrTypes: rowFiltersElemAttrTypes()}, rowFiltersValues)
		diags.Append(rowFiltersD...)
		state.RowFilters = rowFiltersList
	} else {
		state.RowFilters = types.ListNull(types.ObjectType{AttrTypes: rowFiltersElemAttrTypes()})
	}
	if resp.WriteMode != nil && string(*resp.WriteMode) != "" {
		state.WriteMode = types.StringValue(string(*resp.WriteMode))
	} else {
		state.WriteMode = types.StringNull()
	}
	if resp.ApprovalMode != nil && string(*resp.ApprovalMode) != "" {
		state.ApprovalMode = types.StringValue(string(*resp.ApprovalMode))
	} else {
		state.ApprovalMode = types.StringNull()
	}
	if resp.ApprovalAutoMaxRows != nil {
		state.ApprovalAutoMaxRows = types.Int64Value(int64(*resp.ApprovalAutoMaxRows))
	} else {
		state.ApprovalAutoMaxRows = types.Int64Null()
	}
	if resp.ApprovalTimeoutSeconds != nil {
		state.ApprovalTimeoutSeconds = types.Int64Value(int64(*resp.ApprovalTimeoutSeconds))
	} else {
		state.ApprovalTimeoutSeconds = types.Int64Null()
	}
	if resp.MigrationSafety != nil && string(*resp.MigrationSafety) != "" {
		state.MigrationSafety = types.StringValue(string(*resp.MigrationSafety))
	} else {
		state.MigrationSafety = types.StringNull()
	}
	if resp.EgressBytesPerDay != nil {
		state.EgressBytesPerDay = types.Int64Value(int64(*resp.EgressBytesPerDay))
	} else {
		state.EgressBytesPerDay = types.Int64Null()
	}
	if resp.MaxAffectedRows != nil {
		state.MaxAffectedRows = types.Int64Value(int64(*resp.MaxAffectedRows))
	} else {
		state.MaxAffectedRows = types.Int64Null()
	}
	if resp.ContentScanMode != nil && string(*resp.ContentScanMode) != "" {
		state.ContentScanMode = types.StringValue(string(*resp.ContentScanMode))
	} else {
		state.ContentScanMode = types.StringNull()
	}
	if resp.ContentScanMaxBytes != nil {
		state.ContentScanMaxBytes = types.Int64Value(int64(*resp.ContentScanMaxBytes))
	} else {
		state.ContentScanMaxBytes = types.Int64Null()
	}
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
