// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*projectResource)(nil)
	_ resource.ResourceWithConfigure   = (*projectResource)(nil)
	_ resource.ResourceWithImportState = (*projectResource)(nil)
)

type projectResource struct {
	client *pgbeam.Client
}

type projectResourceModel struct {
	ID                     types.String `tfsdk:"id"`
	OrgID                  types.String `tfsdk:"org_id"`
	Name                   types.String `tfsdk:"name"`
	Description            types.String `tfsdk:"description"`
	Tags                   types.List   `tfsdk:"tags"`
	Cloud                  types.String `tfsdk:"cloud"`
	SelfHosted             types.Bool   `tfsdk:"self_hosted"`
	ProxyHost              types.String `tfsdk:"proxy_host"`
	QueriesPerSecond       types.Int64  `tfsdk:"queries_per_second"`
	BurstSize              types.Int64  `tfsdk:"burst_size"`
	MaxConnections         types.Int64  `tfsdk:"max_connections"`
	AllowedCidrs           types.List   `tfsdk:"allowed_cidrs"`
	DefaultPolicyProfileID types.String `tfsdk:"default_policy_profile_id"`
	Residency              types.String `tfsdk:"residency"`
	AgentsDisabled         types.Bool   `tfsdk:"agents_disabled"`
	DatabaseCount          types.Int64  `tfsdk:"database_count"`
	ActiveConnections      types.Int64  `tfsdk:"active_connections"`
	Status                 types.String `tfsdk:"status"`
	CreatedAt              types.String `tfsdk:"created_at"`
	UpdatedAt              types.String `tfsdk:"updated_at"`
	PrimaryDatabaseID      types.String `tfsdk:"primary_database_id"`
}

type allowedCidrsElemModel struct {
	Cidr  types.String `tfsdk:"cidr"`
	Label types.String `tfsdk:"label"`
}

func NewProjectResource() resource.Resource {
	return &projectResource{}
}

func allowedCidrsElemAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"cidr":  types.StringType,
		"label": types.StringType,
	}
}

func (r *projectResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project"
}

func (r *projectResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a PgBeam project with a primary database.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique project identifier (prefixed).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"org_id": schema.StringAttribute{
				Description: "Better Auth organization ID that owns this project.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Human-readable project name.",
				Required:    true,
			},
			"description": schema.StringAttribute{
				Description: "Optional project description.",
				Optional:    true,
			},
			"tags": schema.ListAttribute{
				Description: "User-defined labels applied to the project.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"cloud": schema.StringAttribute{
				Description: "Cloud provider where the project runs.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"self_hosted": schema.BoolAttribute{
				Description: "When true, this project's data plane runs in the customer's own VPC/cluster (BYOC): the control plane does not provision hosted infra, and a self-hosted proxy dials home over the config/audit gRPC stream. Requires the Scale or enterprise plan.\n",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplace(),
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"proxy_host": schema.StringAttribute{
				Description: "Proxy hostname for connecting through PgBeam (e.g., myproject.proxy.pgbeam.app).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"queries_per_second": schema.Int64Attribute{
				Description: "Maximum queries per second for this project. 0 means unlimited.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"burst_size": schema.Int64Attribute{
				Description: "Burst allowance above the steady-state rate. 0 uses queries_per_second as burst.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"max_connections": schema.Int64Attribute{
				Description: "Maximum concurrent proxy connections. 0 means unlimited.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"allowed_cidrs": schema.ListNestedAttribute{
				Description: "IP filtering rules as CIDR ranges with optional labels. When non-empty, only connections from matching IPs are accepted. Empty array means all IPs are allowed (default). Both IPv4 (e.g. 10.0.0.0/8) and IPv6 (e.g. 2001:db8::/32) are supported.\n",
				Optional:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"cidr": schema.StringAttribute{
							Description: "CIDR range in IPv4 (e.g. 203.0.113.0/24) or IPv6 (e.g. 2001:db8::/32) notation. A plain IP without prefix length defaults to /32 (IPv4) or /128 (IPv6).\n",
							Required:    true,
						},
						"label": schema.StringAttribute{
							Description: "Optional human-readable label for this CIDR entry (e.g. \"Office\", \"VPC\").",
							Optional:    true,
						},
					},
				},
			},
			"default_policy_profile_id": schema.StringAttribute{
				Description: "When set, passthrough/human connections are enforced against this policy profile.",
				Optional:    true,
			},
			"residency": schema.StringAttribute{
				Description: "Data-residency requirement for the project. \"any\" (default) lets queries be served from the nearest data-plane metro. \"us\" or \"eu\" require the serving metro to be in that jurisdiction; the proxy fails a connection closed when it is served from a metro outside the required jurisdiction, so regulated workloads never process outside their permitted region.\n",
				Optional:    true,
			},
			"agents_disabled": schema.BoolAttribute{
				Description: "Project-level kill-switch. When true, ALL agent-credential connections to this project are blocked at the proxy and live agent sessions are dropped within seconds. Passthrough/human connections are unaffected.\n",
				Optional:    true,
			},
			"database_count": schema.Int64Attribute{
				Description: "Number of databases attached to this project.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"active_connections": schema.Int64Attribute{
				Description: "Current active connections (latest metrics snapshot). 0 when no metrics data.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"status": schema.StringAttribute{
				Description: "Project lifecycle status.",
				Optional:    true,
				Computed:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "When the project was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the project was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"primary_database_id": schema.StringAttribute{
				Description: "ID of the primary database created with this project.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *projectResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *projectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan projectResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.CreateProjectRequest{
		OrgId: plan.OrgID.ValueString(),
		Name:  plan.Name.ValueString(),
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		createReq.Description = &v
	}

	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		var v []string
		resp.Diagnostics.Append(plan.Tags.ElementsAs(ctx, &v, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Tags = &v
	}

	result, err := r.client.Projects.CreateProject(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating project", err.Error())
		return
	}

	updateReq := pgbeam.UpdateProjectRequest{}
	needsPostCreateUpdate := false
	if !plan.AllowedCidrs.IsNull() && !plan.AllowedCidrs.IsUnknown() {
		var allowedCidrsElems []allowedCidrsElemModel
		resp.Diagnostics.Append(plan.AllowedCidrs.ElementsAs(ctx, &allowedCidrsElems, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		allowedCidrsEntries := make([]pgbeam.CidrEntry, len(allowedCidrsElems))
		for i, e := range allowedCidrsElems {
			tmpLabel := e.Label.ValueString()
			allowedCidrsEntries[i] = pgbeam.CidrEntry{
				Cidr:  e.Cidr.ValueString(),
				Label: &tmpLabel,
			}
		}
		updateReq.AllowedCidrs = &allowedCidrsEntries
		needsPostCreateUpdate = true
	}
	if !plan.DefaultPolicyProfileID.IsNull() && !plan.DefaultPolicyProfileID.IsUnknown() {
		v := plan.DefaultPolicyProfileID.ValueString()
		updateReq.DefaultPolicyProfileId = &v
		needsPostCreateUpdate = true
	}
	if !plan.Residency.IsNull() && !plan.Residency.IsUnknown() {
		v := pgbeam.DataResidency(plan.Residency.ValueString())
		updateReq.Residency = &v
		needsPostCreateUpdate = true
	}
	if !plan.AgentsDisabled.IsNull() && !plan.AgentsDisabled.IsUnknown() {
		v := plan.AgentsDisabled.ValueBool()
		updateReq.AgentsDisabled = &v
		needsPostCreateUpdate = true
	}
	if !plan.Status.IsNull() && !plan.Status.IsUnknown() {
		v := pgbeam.ProjectStatus(plan.Status.ValueString())
		updateReq.Status = &v
		needsPostCreateUpdate = true
	}
	if needsPostCreateUpdate {
		if _, err := r.client.Projects.UpdateProject(ctx, result.Project.Id, updateReq); err != nil {
			resp.Diagnostics.AddError("Error setting rate limits on newly created project", err.Error())
			return
		}
		updated, err := r.client.Projects.GetProject(ctx, result.Project.Id)
		if err != nil {
			resp.Diagnostics.AddError("Error reading project after rate limit update", err.Error())
			return
		}
		result.Project = *updated
	}

	plan.ID = types.StringValue(result.Project.Id)
	r.mapProjectToState(ctx, &plan, &result.Project, &resp.Diagnostics)

	if result.Database != nil {
		plan.PrimaryDatabaseID = types.StringValue(result.Database.Id)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *projectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state projectResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	Project, err := r.client.Projects.GetProject(ctx, state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading project", err.Error())
		return
	}

	r.mapProjectToState(ctx, &state, Project, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *projectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan projectResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state projectResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateReq := pgbeam.UpdateProjectRequest{}
	hasChanges := false

	if !plan.Name.Equal(state.Name) {
		v := plan.Name.ValueString()
		updateReq.Name = &v
		hasChanges = true
	}

	if !plan.Description.Equal(state.Description) {
		v := plan.Description.ValueString()
		updateReq.Description = &v
		hasChanges = true
	}

	if !plan.Tags.Equal(state.Tags) {
		var v []string
		if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
			resp.Diagnostics.Append(plan.Tags.ElementsAs(ctx, &v, false)...)
			if resp.Diagnostics.HasError() {
				return
			}
		}
		updateReq.Tags = &v
		hasChanges = true
	}

	if !plan.AllowedCidrs.Equal(state.AllowedCidrs) {
		if !plan.AllowedCidrs.IsNull() && !plan.AllowedCidrs.IsUnknown() {
			var allowedCidrsElems []allowedCidrsElemModel
			resp.Diagnostics.Append(plan.AllowedCidrs.ElementsAs(ctx, &allowedCidrsElems, false)...)
			if resp.Diagnostics.HasError() {
				return
			}
			allowedCidrsEntries := make([]pgbeam.CidrEntry, len(allowedCidrsElems))
			for i, e := range allowedCidrsElems {
				tmpLabel := e.Label.ValueString()
				allowedCidrsEntries[i] = pgbeam.CidrEntry{
					Cidr:  e.Cidr.ValueString(),
					Label: &tmpLabel,
				}
			}
			updateReq.AllowedCidrs = &allowedCidrsEntries
		}
		hasChanges = true
	}

	if !plan.DefaultPolicyProfileID.Equal(state.DefaultPolicyProfileID) {
		if plan.DefaultPolicyProfileID.IsNull() {
			empty := ""
			updateReq.DefaultPolicyProfileId = &empty
		} else {
			v := plan.DefaultPolicyProfileID.ValueString()
			updateReq.DefaultPolicyProfileId = &v
		}
		hasChanges = true
	}

	if !plan.Residency.Equal(state.Residency) {
		v := pgbeam.DataResidency(plan.Residency.ValueString())
		updateReq.Residency = &v
		hasChanges = true
	}

	if !plan.AgentsDisabled.Equal(state.AgentsDisabled) {
		v := plan.AgentsDisabled.ValueBool()
		updateReq.AgentsDisabled = &v
		hasChanges = true
	}

	if !plan.Status.Equal(state.Status) {
		v := pgbeam.ProjectStatus(plan.Status.ValueString())
		updateReq.Status = &v
		hasChanges = true
	}

	if hasChanges {
		_, err := r.client.Projects.UpdateProject(ctx, state.ID.ValueString(), updateReq)
		if err != nil {
			resp.Diagnostics.AddError("Error updating project", err.Error())
			return
		}
	}

	Project, err := r.client.Projects.GetProject(ctx, state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading project after update", err.Error())
		return
	}

	plan.ID = state.ID
	plan.PrimaryDatabaseID = state.PrimaryDatabaseID
	r.mapProjectToState(ctx, &plan, Project, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *projectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state projectResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Projects.DeleteProject(ctx, state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting project", err.Error())
	}
}

func (r *projectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	Project, err := r.client.Projects.GetProject(ctx, req.ID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing project", err.Error())
		return
	}

	var state projectResourceModel
	state.ID = types.StringValue(Project.Id)
	r.mapProjectToState(ctx, &state, Project, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *projectResource) mapProjectToState(ctx context.Context, state *projectResourceModel, resp *pgbeam.Project, diags *diag.Diagnostics) {
	state.OrgID = types.StringValue(resp.OrgId)
	state.Name = types.StringValue(resp.Name)
	if resp.Description != nil {
		state.Description = types.StringValue(*resp.Description)
	} else {
		state.Description = types.StringNull()
	}
	if resp.Tags != nil && len(*resp.Tags) > 0 {
		tagValues := make([]attr.Value, len(*resp.Tags))
		for i, t := range *resp.Tags {
			tagValues[i] = types.StringValue(t)
		}
		tagsList, d := types.ListValue(types.StringType, tagValues)
		diags.Append(d...)
		state.Tags = tagsList
	} else {
		state.Tags = types.ListNull(types.StringType)
	}
	if resp.Cloud != nil && string(*resp.Cloud) != "" {
		state.Cloud = types.StringValue(string(*resp.Cloud))
	} else {
		state.Cloud = types.StringNull()
	}
	if resp.SelfHosted != nil {
		state.SelfHosted = types.BoolValue(*resp.SelfHosted)
	} else {
		state.SelfHosted = types.BoolNull()
	}
	if resp.ProxyHost != nil {
		state.ProxyHost = types.StringValue(*resp.ProxyHost)
	} else {
		state.ProxyHost = types.StringNull()
	}
	if resp.QueriesPerSecond != nil {
		state.QueriesPerSecond = types.Int64Value(int64(*resp.QueriesPerSecond))
	} else {
		state.QueriesPerSecond = types.Int64Value(0)
	}
	if resp.BurstSize != nil {
		state.BurstSize = types.Int64Value(int64(*resp.BurstSize))
	} else {
		state.BurstSize = types.Int64Value(0)
	}
	if resp.MaxConnections != nil {
		state.MaxConnections = types.Int64Value(int64(*resp.MaxConnections))
	} else {
		state.MaxConnections = types.Int64Value(0)
	}
	if resp.AllowedCidrs != nil && len(*resp.AllowedCidrs) > 0 {
		allowedCidrsValues := make([]attr.Value, len(*resp.AllowedCidrs))
		for i, e := range *resp.AllowedCidrs {
			labelV := types.StringNull()
			if e.Label != nil {
				labelV = types.StringValue(*e.Label)
			}
			allowedCidrsValues[i] = types.ObjectValueMust(allowedCidrsElemAttrTypes(), map[string]attr.Value{
				"cidr":  types.StringValue(e.Cidr),
				"label": labelV,
			})
		}
		allowedCidrsList, allowedCidrsD := types.ListValue(types.ObjectType{AttrTypes: allowedCidrsElemAttrTypes()}, allowedCidrsValues)
		diags.Append(allowedCidrsD...)
		state.AllowedCidrs = allowedCidrsList
	} else {
		state.AllowedCidrs = types.ListNull(types.ObjectType{AttrTypes: allowedCidrsElemAttrTypes()})
	}
	if resp.DefaultPolicyProfileId != nil {
		state.DefaultPolicyProfileID = types.StringValue(*resp.DefaultPolicyProfileId)
	} else {
		state.DefaultPolicyProfileID = types.StringNull()
	}
	if resp.Residency != nil && string(*resp.Residency) != "" {
		state.Residency = types.StringValue(string(*resp.Residency))
	} else {
		state.Residency = types.StringNull()
	}
	if resp.AgentsDisabled != nil {
		state.AgentsDisabled = types.BoolValue(*resp.AgentsDisabled)
	} else {
		state.AgentsDisabled = types.BoolNull()
	}
	if resp.DatabaseCount != nil {
		state.DatabaseCount = types.Int64Value(int64(*resp.DatabaseCount))
	} else {
		state.DatabaseCount = types.Int64Value(0)
	}
	if resp.ActiveConnections != nil {
		state.ActiveConnections = types.Int64Value(int64(*resp.ActiveConnections))
	} else {
		state.ActiveConnections = types.Int64Value(0)
	}
	if string(resp.Status) != "" {
		state.Status = types.StringValue(string(resp.Status))
	} else {
		state.Status = types.StringNull()
	}
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
