// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/resource"

func pgbeamResources() []func() resource.Resource {
	return []func() resource.Resource{
		NewProjectResource,
		NewDatabaseResource,
		NewReplicaResource,
		NewCustomDomainResource,
		NewCacheRuleResource,
		NewSpendLimitResource,
		NewAgentCredentialResource,
		NewPolicyProfileResource,
		NewWebhookEndpointResource,
		NewSelfHostEnrollmentResource,
		NewHoneytokenResource,
		NewAnomalyRuleResource,
	}
}
