// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*replicaResource)(nil)
	_ resource.ResourceWithConfigure   = (*replicaResource)(nil)
	_ resource.ResourceWithImportState = (*replicaResource)(nil)
)

type replicaResource struct {
	client *pgbeam.Client
}

type replicaResourceModel struct {
	ID         types.String `tfsdk:"id"`
	DatabaseID types.String `tfsdk:"database_id"`
	Host       types.String `tfsdk:"host"`
	Port       types.Int64  `tfsdk:"port"`
	SSLMode    types.String `tfsdk:"ssl_mode"`
	CreatedAt  types.String `tfsdk:"created_at"`
	UpdatedAt  types.String `tfsdk:"updated_at"`
}

func NewReplicaResource() resource.Resource {
	return &replicaResource{}
}

func (r *replicaResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_replica"
}

func (r *replicaResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a read replica for a PgBeam database.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique replica identifier (prefixed).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"database_id": schema.StringAttribute{
				Description: "Parent database ID.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"host": schema.StringAttribute{
				Description: "PostgreSQL replica host.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"port": schema.Int64Attribute{
				Description: "PostgreSQL replica port.",
				Required:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"ssl_mode": schema.StringAttribute{
				Description: "PostgreSQL SSL connection mode.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created_at": schema.StringAttribute{
				Description: "When the replica was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the replica was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *replicaResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *replicaResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan replicaResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.CreateReplicaRequest{
		Host: plan.Host.ValueString(),
		Port: int(plan.Port.ValueInt64()),
	}

	if !plan.SSLMode.IsNull() && !plan.SSLMode.IsUnknown() {
		v := pgbeam.SSLMode(plan.SSLMode.ValueString())
		createReq.SslMode = &v
	}

	result, err := r.client.Projects.CreateReplica(ctx, plan.DatabaseID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating replica", err.Error())
		return
	}

	plan.ID = types.StringValue(result.Id)
	r.mapReplicaToState(&plan, result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *replicaResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state replicaResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	Replica, err := r.findReplica(ctx, state.DatabaseID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading replica", err.Error())
		return
	}

	r.mapReplicaToState(&state, Replica)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update is not implemented — all fields RequiresReplace, so Terraform will
// never call Update. It is included to satisfy the Resource interface.
func (r *replicaResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update Not Supported", "Replica resources are immutable. All changes trigger a replacement.")
}

func (r *replicaResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state replicaResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Projects.DeleteReplica(ctx, state.DatabaseID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting replica", err.Error())
	}
}

func (r *replicaResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: database_id/replica_id")
		return
	}

	databaseID := parts[0]
	replicaID := parts[1]

	Replica, err := r.findReplica(ctx, databaseID, replicaID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing replica", err.Error())
		return
	}

	var state replicaResourceModel
	state.ID = types.StringValue(Replica.Id)
	state.DatabaseID = types.StringValue(databaseID)
	r.mapReplicaToState(&state, Replica)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// findReplica lists replicas and returns the one matching the given id.
// Returns a not-found error if no match is found.
func (r *replicaResource) findReplica(ctx context.Context, databaseID string, ReplicaID string) (*pgbeam.Replica, error) {
	var pageToken *string
	for {
		params := &pgbeam.ListReplicasParams{
			PageToken: pageToken,
		}
		listResp, err := r.client.Projects.ListReplicas(ctx, databaseID, params)
		if err != nil {
			return nil, err
		}
		for _, Replica := range listResp.Replicas {
			if Replica.Id == ReplicaID {
				return &Replica, nil
			}
		}
		if listResp.NextPageToken == nil || *listResp.NextPageToken == "" {
			break
		}
		pageToken = listResp.NextPageToken
	}
	return nil, &pgbeam.APIError{StatusCode: 404, Status: "404 Not Found", Body: fmt.Sprintf("replica %s not found", ReplicaID)}
}

func (r *replicaResource) mapReplicaToState(state *replicaResourceModel, resp *pgbeam.Replica) {
	state.DatabaseID = types.StringValue(resp.DatabaseId)
	state.Host = types.StringValue(resp.Host)
	state.Port = types.Int64Value(int64(resp.Port))
	if string(resp.SslMode) != "" {
		state.SSLMode = types.StringValue(string(resp.SslMode))
	} else {
		state.SSLMode = types.StringNull()
	}
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
