// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*webhookEndpointResource)(nil)
	_ resource.ResourceWithConfigure   = (*webhookEndpointResource)(nil)
	_ resource.ResourceWithImportState = (*webhookEndpointResource)(nil)
)

type webhookEndpointResource struct {
	client *pgbeam.Client
}

type webhookEndpointResourceModel struct {
	ID          types.String `tfsdk:"id"`
	ProjectID   types.String `tfsdk:"project_id"`
	URL         types.String `tfsdk:"url"`
	Format      types.String `tfsdk:"format"`
	EventTypes  types.List   `tfsdk:"event_types"`
	Enabled     types.Bool   `tfsdk:"enabled"`
	Description types.String `tfsdk:"description"`
	CreatedAt   types.String `tfsdk:"created_at"`
	UpdatedAt   types.String `tfsdk:"updated_at"`
	Secret      types.String `tfsdk:"secret"`
}

func NewWebhookEndpointResource() resource.Resource {
	return &webhookEndpointResource{}
}

func (r *webhookEndpointResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_webhook_endpoint"
}

func (r *webhookEndpointResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a webhook endpoint that receives project audit and anomaly event deliveries. The signing secret is write-only and never returned by the API.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique webhook endpoint identifier (prefixed).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Description: "Owning project ID.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"url": schema.StringAttribute{
				Description: "HTTPS endpoint that receives event deliveries.",
				Required:    true,
			},
			"format": schema.StringAttribute{
				Description: "Payload format for delivered events.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("json"),
			},
			"event_types": schema.ListAttribute{
				Description: "Event types to deliver. Empty means all events.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"enabled": schema.BoolAttribute{
				Description: "Whether deliveries are active for this endpoint.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
			},
			"description": schema.StringAttribute{
				Description: "Human-readable label for the endpoint.",
				Optional:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "When the endpoint was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the endpoint was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"secret": schema.StringAttribute{
				Description: "Shared secret used to sign delivery payloads. Write-only.",
				Optional:    true,
				Sensitive:   true,
			},
		},
	}
}

func (r *webhookEndpointResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *webhookEndpointResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan webhookEndpointResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.WebhookEndpointInput{
		Url: plan.URL.ValueString(),
	}

	if !plan.Format.IsNull() && !plan.Format.IsUnknown() {
		v := pgbeam.WebhookEndpointInputFormat(plan.Format.ValueString())
		createReq.Format = &v
	}

	if !plan.EventTypes.IsNull() && !plan.EventTypes.IsUnknown() {
		var v []string
		resp.Diagnostics.Append(plan.EventTypes.ElementsAs(ctx, &v, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		eventTypesValues := make([]pgbeam.WebhookEventType, len(v))
		for i, s := range v {
			eventTypesValues[i] = pgbeam.WebhookEventType(s)
		}
		createReq.EventTypes = &eventTypesValues
	}

	if !plan.Enabled.IsNull() && !plan.Enabled.IsUnknown() {
		v := plan.Enabled.ValueBool()
		createReq.Enabled = &v
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		createReq.Description = &v
	}

	if !plan.Secret.IsNull() && !plan.Secret.IsUnknown() {
		v := plan.Secret.ValueString()
		createReq.Secret = &v
	}

	result, err := r.client.Webhooks.CreateWebhookEndpoint(ctx, plan.ProjectID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating webhook endpoint", err.Error())
		return
	}

	plan.ID = types.StringValue(result.Id)
	r.mapWebhookEndpointToState(ctx, &plan, result, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *webhookEndpointResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state webhookEndpointResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	WebhookEndpoint, err := r.client.Webhooks.GetWebhookEndpoint(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading webhook endpoint", err.Error())
		return
	}

	r.mapWebhookEndpointToState(ctx, &state, WebhookEndpoint, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *webhookEndpointResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan webhookEndpointResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state webhookEndpointResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	hasChanges := !plan.URL.Equal(state.URL) ||
		!plan.Format.Equal(state.Format) ||
		!plan.EventTypes.Equal(state.EventTypes) ||
		!plan.Enabled.Equal(state.Enabled) ||
		!plan.Description.Equal(state.Description) ||
		!plan.Secret.Equal(state.Secret)

	updateReq := pgbeam.WebhookEndpointInput{
		Url: plan.URL.ValueString(),
	}

	if !plan.Format.IsNull() && !plan.Format.IsUnknown() {
		v := pgbeam.WebhookEndpointInputFormat(plan.Format.ValueString())
		updateReq.Format = &v
	}

	if !plan.EventTypes.IsNull() && !plan.EventTypes.IsUnknown() {
		var v []string
		resp.Diagnostics.Append(plan.EventTypes.ElementsAs(ctx, &v, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		eventTypesValues := make([]pgbeam.WebhookEventType, len(v))
		for i, s := range v {
			eventTypesValues[i] = pgbeam.WebhookEventType(s)
		}
		updateReq.EventTypes = &eventTypesValues
	}

	if !plan.Enabled.IsNull() && !plan.Enabled.IsUnknown() {
		v := plan.Enabled.ValueBool()
		updateReq.Enabled = &v
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		updateReq.Description = &v
	}

	if !plan.Secret.IsNull() && !plan.Secret.IsUnknown() {
		v := plan.Secret.ValueString()
		updateReq.Secret = &v
	}

	if hasChanges {
		_, err := r.client.Webhooks.UpdateWebhookEndpoint(ctx, state.ProjectID.ValueString(), state.ID.ValueString(), updateReq)
		if err != nil {
			resp.Diagnostics.AddError("Error updating webhook endpoint", err.Error())
			return
		}
	}

	WebhookEndpoint, err := r.client.Webhooks.GetWebhookEndpoint(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading webhook endpoint after update", err.Error())
		return
	}

	plan.ID = state.ID
	r.mapWebhookEndpointToState(ctx, &plan, WebhookEndpoint, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *webhookEndpointResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state webhookEndpointResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Webhooks.DeleteWebhookEndpoint(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting webhook endpoint", err.Error())
	}
}

func (r *webhookEndpointResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: project_id/webhook_id")
		return
	}

	projectID := parts[0]
	webhookID := parts[1]

	WebhookEndpoint, err := r.client.Webhooks.GetWebhookEndpoint(ctx, projectID, webhookID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing webhook endpoint", err.Error())
		return
	}

	var state webhookEndpointResourceModel
	state.ID = types.StringValue(WebhookEndpoint.Id)
	state.ProjectID = types.StringValue(projectID)
	// Secret cannot be read back from API
	state.Secret = types.StringValue("")
	r.mapWebhookEndpointToState(ctx, &state, WebhookEndpoint, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *webhookEndpointResource) mapWebhookEndpointToState(ctx context.Context, state *webhookEndpointResourceModel, resp *pgbeam.WebhookEndpoint, diags *diag.Diagnostics) {
	state.ProjectID = types.StringValue(resp.ProjectId)
	state.URL = types.StringValue(resp.Url)
	if string(resp.Format) != "" {
		state.Format = types.StringValue(string(resp.Format))
	} else {
		state.Format = types.StringNull()
	}
	if resp.EventTypes != nil && len(*resp.EventTypes) > 0 {
		tagValues := make([]attr.Value, len(*resp.EventTypes))
		for i, t := range *resp.EventTypes {
			tagValues[i] = types.StringValue(string(t))
		}
		tagsList, d := types.ListValue(types.StringType, tagValues)
		diags.Append(d...)
		state.EventTypes = tagsList
	} else {
		state.EventTypes = types.ListNull(types.StringType)
	}
	state.Enabled = types.BoolValue(resp.Enabled)
	if resp.Description != nil {
		state.Description = types.StringValue(*resp.Description)
	} else {
		state.Description = types.StringNull()
	}
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
